#!/bin/bash

current_branch=`git rev-parse --abbrev-ref HEAD`
not_allowed_branches='master|production|prod|staging|stage'
error_message="\033[0;31mAborting commit. \033[0mYou are not allowed to commit into \033[0;32m$current_branch\033[0m branch"

if [[ ${current_branch} =~ ${not_allowed_branches} ]]; then
    echo -e "$error_message" >&2
    exit 1
fi
